### PR TITLE
added portfolio

### PR DESCRIPTION
**Pull request by Shaily20**

### CODE REVIEW

**Comment by Shaily20** [comment]
Added Animation and Todolist

**Comment by aayusharora** [comment]
@Shaily20 Thanks, but you need to remove the images and replace them by hosted URLS

**Comment by Shaily20** [comment]
Removed Images

**Comment by Shaily20** [comment]
Pls merge it.Made the required changes

**Comment by aayusharora** [comment]
Thanks @Shaily20

**Pull request merged**
